### PR TITLE
Improvements to spThin

### PR DESCRIPTION
**Pull request by paleo13**
Hi,

Awesome work with spThin.

I was looking into using your package a few days ago, and found it wasn't fast enough to work with datasets containing lots of points.

So I took a look at the source code and implemented thin.algorithm in c++ using Rcpp. Then, for kicks, I rewrote some of the code to make it easer to work with in R (in my opinion). These changes included:

-  an S4 SpThin class which is returned by the thin function;
- thin function is now compatible with sp::SpatialPoints and sp::SpatialPointsDataFrame classes;
- the plot and summary functions are now S3 methods for this class;
- the plot graphics are now generated using ggplot2;
- some extra methods ([[, samples, nreps, and data) to make accessing results easier
- saving the results to disk is now handled by a S3 write method. 

Let me know if you have any questions or ideas for further improvement,

Cheers,

Jeff

### CODE REVIEW

**Comment by mlammens** [comment]
Hi Jeff, 

These look like awesome additions - thanks a lot! I'm heading out for a trip to South Africa today, so I might not merge this and submit an updated package to CRAN until I get back (depending on internet access), so if not sooner, then definitely after the 23rd of July I'll take care of it. And of course, I'll list you as a package author on any new CRAN submission (unless you don't want to be). 

Matt

**Comment by paleo13** [comment]
No worries! 

Sure! After I sent this last night, I was thinking of writing an option to thin records by overlaying them on a grid and randomly selecting records inside each grid cell to thin datasets with 100k+ records. So let's wait till I've finished that before submitting it to CRAN?

Yeah, that would be awesome if I could be listed as a package author!

Jeff

**Comment by paleo13** [comment]
Hi,

I've finished making all the changes (I hope/think). 

Have a look at the vignette, and let me know what you think?

I haven't uploaded a package to CRAN before. I've run it though the CRAN checks using devtools and there's no errors, warnings or notes, so from what I understand it should be good. 

Jeff

**Comment by paleo13** [comment]
Just found some missing dependencies, it should be good now.

**Comment by mlammens** [comment]
Jeff, these changes look great. I'd like to merge it and test out the package locally, then I'll compile it for submission to CRAN. The only edit I would like to see first (or I can do it after the merge, if you'd prefer), is a wording change in the docs. Strictly speaking, spThin doesn't "remove sampling bias", but rather it "ameliorates sampling bias". Let me know if you want to make this change, or if I should. If the later, I'll merge and edit later.

Matt

**Comment by paleo13** [comment]
Yeah, that sounds great. 

I agree with you about it not removing but ameliorating bias. I had a quick look through the docs for 'remove' and replaced it with 'ameliorate'. This only occurred in the DESCRIPTION and README.md. 

Jeff

**Comment by mlammens** [comment]
@paleo13 I merged your pull request and started playing around with the new spThin function. It looks very interesting. I added a number of "Issues" to this project related to either current errors that need to be addressed or changes I think the Vignette in particular needs. One thing I noticed is that it's not clear how to get each of the thinned datasets out of the spThin object. Am I missing something?

**Pull request merged**
