### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by paleo13**
Hi, 

I fixed the bug issues regarding the heuristic algorithm, and the updated the vignette to explain more about the timeout with lp_solve.

I also made a few changes regarding the summary methods for SpThin and SpRarefy classes, so it calculates the actual minimum distances between retained records and prints them.

Cheers,

Jeff

### CODE REVIEW

**Comment by paleo13** [comment]
I added in automatic CRAN checks (using Travis CI) and testing coverage checks (using coveralls.io) to the README.md over the weekend. 

Let me know if you come across any more bugs or issues.

Jeff

**Comment by mlammens** [comment]
Thanks Jeff. I'm going to have a look at this tonight or tomorrow, and will get back to you.

**Comment by mlammens** [comment]
Hi Jeff - I've merged your pull request and made a few modifications, mostly related to adding you as an author. There was one fix I made at lines 212 and 213 in the vignette Rmd file. I assumed you wanted to be pulling from the `t1` object, rather than `r1`.

I've never worked with any tools like TravisCI, or real testing for that matter. If you have the time, could you send me a note via email about this process? Is it setup elsewhere (i.e., not in GitHub)? Does it mean that the package should be ready to submit to CRAN? 

I added a reference to the package by itself to the README, and have not added a CITATION file yet. I can't add you to the Ecography paper retrospectively, so I think this is the best approach to give you credit for all the work you did for now. Do you agree? Also, I added your role as a maintainer (and author), but if you would rather not be listed as such, just let me know.

**Comment by paleo13** [comment]
Brilliant! Thanks for catching that. Yeah, that sounds great. I'm running devtools::check() over it now and it doesn't like having two maintainers, so I guess if there can only be one, that should be you?

Sure, I'll send you info on Travis CI and coveralls.io.

I think so. I haven't submitted a package to CRAN before, and have been going from stuff in http://r-pkgs.had.co.nz.

**Comment by mlammens** [comment]
That's unfortunate that we can't both be maintainers. Yeah, for now I'd prefer to be maintainer since the package is still relatively new and I work so closely with most of the folks I know who use it. We should add something to the README.md though emphasizing your role. Does that sounds ok to you?

**Comment by paleo13** [comment]
Sure, that sounds great.

Once that's done, and the Travis CI and coveralls stuff is done, I think it'll be ready for CRAN?

**Comment by mlammens** [comment]
Yup. Should be able to submit it Friday, my time (I'm in a workshop tomorrow).

**Pull request merged**
